# Generated by Django 4.2.4 on 2024-02-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productCode', models.IntegerField()),
                ('productDescription', models.CharField()),
                ('productPrice', models.IntegerField()),
                ('productImageUrl', models.CharField(blank=True, max_length=200, null=True)),
                ('productStatus', models.BooleanField()),
            ],
        ),
    ]
