# Generated by Django 4.2.6 on 2024-04-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageUrl',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
