# Generated by Django 4.2.6 on 2024-04-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
    ]
