# Generated by Django 4.2.6 on 2024-04-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
