# Generated by Django 4.2.6 on 2024-04-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productCode', models.IntegerField()),
                ('productDescription', models.CharField()),
                ('productPrice', models.IntegerField()),
                ('productImageUrl', models.ImageField(null=True, upload_to='productos/')),
                ('productStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryDescription', models.CharField(max_length=200)),
            ],
        ),
    ]
