# Generated by Django 4.2.6 on 2024-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageUrl',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
