# Generated by Django 4.2.6 on 2024-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_productimageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='categoryStatus',
            field=models.BooleanField(default=True),
        ),
    ]
