# Generated by Django 4.2.6 on 2024-04-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_productcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='CategoryProduct',
        ),
    ]
