# Generated by Django 4.2.6 on 2024-04-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_productcategory_categoryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(max_length=100),
        ),
    ]
