# Generated by Django 4.2.6 on 2024-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStock',
            field=models.IntegerField(null=True),
        ),
    ]
