# Generated by Django 4.2.6 on 2024-05-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_cart_quantity_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct'),
        ),
    ]
