# Generated by Django 4.2.6 on 2024-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='transaction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
