# Generated by Django 4.2.6 on 2024-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_delivery_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=200),
        ),
    ]
