# Generated by Django 4.2.4 on 2024-09-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliveryStataus',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(),
        ),
    ]
