# Generated by Django 4.2.4 on 2024-09-08 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_delivery_deliverystataus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='deliveryStataus',
            new_name='deliveryStatus',
        ),
    ]
