# Generated by Django 4.2.4 on 2024-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_rename_name_delivery_namedel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='nameDel',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
