# Generated by Django 4.2.4 on 2024-09-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_delivery_namedel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='nameDel',
            new_name='name',
        ),
    ]
