# Generated by Django 4.2.4 on 2024-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_delivery_deliverystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
