# Generated by Django 4.2.4 on 2024-09-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_delivery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='deliveryStatus',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
