# Generated by Django 4.2.4 on 2023-11-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
